### ISSUE TITLE
Latest master does not work

### ISSUE THREAD

**Issue by umpirsky** [jsor/jcarousel#388]
Hi.

I forked this project in order to prevent selecting elements on prev/next double click. But looks like it does not work. No errors in console, but no carousel behavior as well. I opened [test page](https://github.com/jsor/jcarousel/blob/master/test/unit/index.html) and I got:

```
jquery.jcarousel: constructor sets element (1, 1, 2)Rerun

    #jcarousel1 (element exists)
    #jcarousel1 (element is jQuery object)
    Source:     

    ([object Object])@file:///home/umpirsky/Projects/JavaScript/jcarousel/test/unit/jquery.jcarousel.js:11
```

```
jquery.jcarousel: _init() sets list (1, 0, 1)Rerun

    Died on test #1 ((function (selector, context) {return new jQuery.fn.init(selector, context, rootjQuery);}))@file:///home/umpirsky/Projects/JavaScript/jcarousel/test/unit/jquery.jcarousel.js:53 ([object HTMLDocument],[object Array])@http://code.jquery.com/jquery-latest.js:1075 ([object HTMLDocument],[object Array])@http://code.jquery.com/jquery-latest.js:1193 ()@http://code.jquery.com/jquery-latest.js:435 ([object Event])@http://code.jquery.com/jquery-latest.js:949 : $("#jcarousel1").data("jcarousel").list.get is not a function
    Source:     

    ([object Object])@file:///home/umpirsky/Projects/JavaScript/jcarousel/test/unit/jquery.jcarousel.js:58
```

Client is `Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:12.0) Gecko/20100101 Firefox/12.0`.

My page works with version 0.2.8 from http://sorgalla.com/jcarousel/, but when I replace plugin with latest master, it stops working.

Should current version from master work?
