### ISSUE TITLE
jquery 3.0

### ISSUE THREAD

**Issue by val4o0o0** [jsor/jcarousel#800]
I'm getting: 
carousel.js:16 Uncaught TypeError: this.clip.size is not a function
in my event log.

**Comment by jsor** [comment]
Which version are you using? The current 0.3.x or the older 0.2.x?

**Comment by val4o0o0** [comment]
Jquery 3.0 beta 1. The problem is size() function which is deprecated. I solve problem by myself. size() > length (length is supported by jquery 1.0 >) 
I rewrite the code. (https://jsfiddle.net/Lwx1h8aq/) - here is, minified version. (working with 3.0.x)
I write to you, to fix this problem for all other users which using this pretty carousel :)

**Comment by val4o0o0** [comment]
aww.. about the carousel version, i don't know, maybe 0.2.x..

**Comment by jsor** [comment]
Sorry for the delay. I've released [0.2.10](https://github.com/jsor/jcarousel/releases/tag/0.2.10) which should fix this.

**Comment by AbdealiJK** [comment]
Guess this can be closed then ?

**Comment by val4o0o0** [comment]
yep :)

**Comment by jsor** [comment]
@val4o0o0 Then feel free to close when your issue has been resolved :)
